### ISSUE TITLE
Challenge from Specify - Text Styles as CSS classes within CSS @layer

### ISSUE THREAD

**Issue by ChucKN0risK** [Specifyapp/specify-challenge-us#1]
### Design to code process

On the design side, our tokens are defined as Figma Styles and Figma Variables. We have a light and a dark theme.

On the frontend side, we expect the design tokens to be delivered as CSS variables inside [a cascade layer](https://developer.mozilla.org/en-US/docs/Web/CSS/@layer).

### Output file extension

.css

### Output file content

```css
/* text-styles.css */
@layer utilities {
  .text-title-text {
    font-family: 'Inter', serif;
    font-weight: 600;
    font-size: 16px;
    line-height: 1.2;
  }
    
  .text-body-text {
    font-family: 'Inter', serif;
    font-weight: 500;
    font-size: 13px;
    line-height: 1.5;
  }   
}
```
